apisix:
  node_listen: 9080          
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               
      - 0.0.0.0/0         

    admin_key:
      - name: "admin"
        key: a3b7d5e812c49f6038e2ab91f4d6c7e5
        role: admin                 

      - name: "viewer"
        key: f9c2a6d84e713b05d7f1c38a92b4e650
        role: viewer

  etcd:
    host:                           
      - "http://etcd:2379"         
    prefix: "/apisix"              
    timeout: 30                    

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091